apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-demo
  namespace: argo1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pstefanovic/testing-argocd.git
    path: apps/mock-demo
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
