apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-demo
  namespace: argo1
spec:
  project: default
  source:
    repoURL: https://github.com/pstefanovic/testing-argocd.git
    path: apps/mock-demo
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy: {}
