---
# Source: mock-datafridge/charts/echo-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-echo-server
  labels:
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: release-name
---
# Source: mock-datafridge/charts/echo-server/templates/configmap.yaml
apiVersion:  v1
kind: ConfigMap
metadata:
  name: release-name-echo-server
data:
    PORT: "8880"
    LOGS__IGNORE__PING: "false"
    ENABLE__HOST: "true"
    ENABLE__HTTP: "true"
    ENABLE__REQUEST: "true"
    ENABLE__COOKIES: "true"
    ENABLE__ENVIRONMENT: "true"
    ENABLE__FILE: "true"
    ENABLE__HEADER: "true"
---
# Source: mock-datafridge/charts/echo-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-echo-server
  labels:
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/name: echo-server
spec:
  type: ClusterIP
  ports:
    - port: 8880
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: release-name
---
# Source: mock-datafridge/charts/echo-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/config: ee0bfac1cdd1539c9446cab9598e4d5931d31d5e368df3017fc909b2885ff5c3
      labels:
        app.kubernetes.io/name: echo-server
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-echo-server
      securityContext:
        {}
      containers:
        - name: echo-server
          securityContext:
            {}
          image: "ealen/echo-server:0.6.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8880
              protocol: TCP
          envFrom:
            - configMapRef:
                name: release-name-echo-server
          livenessProbe:
            httpGet:
                path: /ping
                httpHeaders:
                - name: x-echo-code
                  value: "200"
                port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
---
# Source: mock-datafridge/charts/echo-server/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-echo-server-test-connection"
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-echo-server:8880']
  restartPolicy: Never
